---
title: "Amaten Tracker"
output:
  flexdashboard::flex_dashboard:
    orientation: rows 
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(dplyr)
library(ggplot2)
library(scales)
library(lubridate)
library(dygraphs)
library(xts)
```

```{r data, include=FALSE}
amaten <- read.csv("history2.csv") %>%
  mutate(
    timestamp = as.POSIXct(timestamp, tz = "Japan"),
    ratio = selling_price/face_price,
    date = as.Date(timestamp, tz = "Japan")
  )
```

```{r parameter, include=FALSE}
lb_chart <- 0.875

NUM_YM_MONTHLY <- 5
NUM_YW_WEEKLY <- 5
```


History
=======================================================================

Sidebar{.sidebar}
-----------------------------------------------------------------------
target calendar range
```{r}
dateInput(
  "start",
  label = "start of date range",
  value = min(amaten$date)
)

dateInput(
  "end",
  label = "end of date range",
  value = max(amaten$date)
)

numericInput(
  "maxprice",
  label = "Max price. Include below:",
  value = 200000,
  step = 10000
 )

numericInput(
  "ranker",
  label = "Target rank. Include top of:",
  value = 5,
  min = 1
)


```



history of ratio {data-height=800}
-----------------------------------------------------------------------

```{r}
target <- reactive({
amaten %>%
  filter(between(date, input$start, input$end)) %>%
  arrange(timestamp, ratio) %>%
  group_by(timestamp) %>%
  filter(
    selling_price <= input$maxprice,
    row_number() <= input$ranker
  ) %>%
  ungroup
})
```

### history of ratio 
```{r}
renderDygraph({
  target() %>%
    group_by(timestamp) %>%
    summarise(ratio = mean(ratio)) %>%
    xts(x = .[["ratio"]], order.by = .[["timestamp"]]) %>%
    dygraph %>%
    dySeries("V1", label = "Ave. Ratio") %>%
    dyRangeSelector(height = 20) %>%
    #dyOptions(drawPoints = TRUE, pointSize = 3, digitsAfterDecimal = 4) %>%
    dyHighlight(highlightCircleSize = 5) %>%
    dyAxis("y", label = "ave.ratio", valueRange=c(lb_chart, 1))
})
```

top record 
----------------------------------------------------------------------

### top record 
```{r global_record}
renderTable({
target() %>%
  arrange(ratio) %>%
  head(10) %>%
  transmute(
    rank = row_number(),
    datetime = as.character(timestamp),
    ratio = as.character(ratio),
    face_price = as.integer(face_price),
    selling_price = as.integer(selling_price)
  )

})
```

### latest observation {data-width=200}
```{r}
renderTable({
target() %>%
  group_by(datetime = as.character(timestamp)) %>%
  summarise(ave.ratio = mean(ratio) %>% format(digits = 4)) %>%
  ungroup %>%
  top_n(10, wt = datetime) %>%
  arrange(desc(datetime))
})
```

<!--
top record {.mobile}
-----------------------------------------------------------------
### history
```{r}
renderPlot({
  target() %>%
    group_by(timestamp) %>%
    summarise(ratio = mean(ratio)) %>%
    ggplot(aes(timestamp, ratio)) +
      geom_line() +
      geom_point() +
      ylim(lb_chart, 1) +
      scale_x_datetime(date_labels="%Y-%m-%d") +
      xlab("") + ylab("ave. ratio")
})
```

###  top record
```{r }
renderTable({
target() %>%
  arrange(ratio) %>%
  head(5) %>%
  transmute(
    datetime = as.character(timestamp),
    ratio = as.character(ratio),
    face_price = as.integer(face_price)
  )

})
```

### latest observation 
```{r}
renderTable({
target() %>%
  group_by(datetime = as.character(timestamp)) %>%
  summarise(ave.ratio = mean(ratio) %>% format(digits = 4)) %>%
  ungroup %>%
  top_n(5, wt = datetime) %>%
  arrange(desc(datetime))
})
```
-->


Seasonality
================================================ 

Sidebar {.sidebar}
-----------------------------------------------------------------------
```{r}
years <- year(amaten$date)
selectInput(
  "y_year",
  label = "filter year",
  choices = years,
  multiple = TRUE,
  selected = years
)

months <- month(amaten$date, label = TRUE, locale = "C")
selectInput(
  "y_month",
  label = "filter month",
  choices = months,
  multiple = TRUE,
  selected = months
)

yms <- floor_date(amaten$date, "month") %>% format("%Y-%m")
selectInput(
  "y_ym",
  label = "filter yearmonth",
  choices = yms,
  multiple = TRUE,
  selected = yms
)

numericInput(
  "y_maxprice",
  label = "Max price. Include below:",
  value = 200000,
  step = 10000
 )

numericInput(
  "y_ranker",
  label = "Target rank. Include top of:",
  value = 5,
  min = 1
) 

```

Yearly
-----------------------------------------

### Yearly
```{r}
target_season <- reactive({
amaten %>%
  mutate(
    year = year(timestamp),
    ym = floor_date(timestamp, "month"),
    rank_ym = dense_rank(as.integer(ym) * -1),
  ) %>%
  filter(
    year %in% input$y_year,
    month(timestamp, label = TRUE, locale = "C") %in% input$y_month,
    format(ym, "%Y-%m") %in% input$y_ym
  ) %>%
  arrange(timestamp, ratio) %>%
  group_by(timestamp) %>%
  filter(
    selling_price <= input$y_maxprice,
    row_number() <= input$y_ranker
  ) %>%
  ungroup
})

renderPlot({
target_season() %>%
  group_by(timestamp, year) %>%
  summarise(ratio = mean(ratio)) %>%
  mutate(
    md = update(timestamp, year = 2018),
    year = factor(year)
  ) %>%
  ggplot(aes(md, ratio)) +
    geom_line(aes(group = year, color = year)) +
    #geom_point(aes(color = year)) +
    ylim(lb_chart,1) +
    scale_x_datetime(date_labels="%b-%d", minor_breaks = date_breaks("day")) +
    xlab("")
  })
```

Periodicaly
------------------------------------------
### Monthly 

```{r}

#renderPlot({
#target_season() %>%
#  filter(year == max(input$y_year)) %>%
#  mutate(
#    dom = day(timestamp) %>% factor,
#    month = month(timestamp, label = TRUE)
#  ) %>%
#  group_by(dom, month) %>%
#  summarise(
#    ratio.mean = mean(ratio),
#    ratio.max = max(ratio),
#    ratio.min = min(ratio)
#  ) %>%
#  ungroup %>%
#  ggplot(aes(dom, ratio.mean)) +
#    geom_line(aes(group = month, color = month)) +
#    geom_pointrange(aes(ymin = ratio.min, ymax = ratio.max, color = month)) +
#    coord_cartesian(ylim=c(lb_chart,1)) +
#    xlab("Day of Month") + ylab("ratio") 
#  })

renderPlot({
target_season() %>%
  filter(rank_ym <= NUM_YM_MONTHLY) %>%
  mutate(
    dom = update(timestamp, year = 2019, month = 1),
    ym = format(ym, "%Y-%m")
  ) %>%
  group_by(dom, ym) %>%
  summarise(ratio = mean(ratio)) %>%
  ggplot(aes(dom, ratio)) +
    geom_line(aes(group = ym, color = ym), alpha = 0.8, size = 0.8) +
    #geom_point(aes(color = ym, shape = ym), alpha = 0.7) +
    coord_cartesian(ylim = c(lb_chart, 1)) +
    scale_x_datetime(
      labels = date_format("%d"),
      breaks = ymd_h(2019010101) + days(0:6 * 5)
    ) +
    xlab("Day of Month") + ylab("ratio")

})
``` 

### Weekly

```{r}
renderPlot({
#target_season() %>%
#  group_by(timestamp) %>%
#  summarise(ratio = mean(ratio)) %>%
#  mutate(dow = wday(timestamp, label = TRUE, locale = "C")) %>%
#  ggplot(aes(dow, ratio)) +
#    geom_boxplot() +
#    ylim(lb_chart, 1) +
#    xlab("Day of Week")

#target_season() %>%
#  filter(rank_ym <= NUM_YM_WEEKLY) %>%
#  mutate(
#    dow = wday(timestamp, label = TRUE),
#    ym = ym %>% format("%Y-%m")
#  ) %>%
#  group_by(dow, ym) %>%
#  summarise(ratio = mean(ratio)) %>%
#  ggplot(aes(ym, dow)) +
#    geom_tile(aes(fill = ratio)) +
#    scale_y_discrete(limits = rev(c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"))) +
#    xlab("") + ylab("")

target_season() %>%
  mutate(
    yw = floor_date(timestamp, "week"),
    rank_yw = dense_rank(as.integer(yw) * -1)
  ) %>%
  filter(rank_yw <= NUM_YW_WEEKLY) %>%
  group_by(ddow = timestamp - yw, yw = factor(yw)) %>%
  summarise(ratio = mean(ratio)) %>%
  ggplot(aes(ddow, ratio)) +
    geom_line(aes(group = yw, color = yw), alpha = 0.8, size = 0.8) +
    scale_x_continuous(breaks = seq(from = 0, by = 1440, length.out = 7), labels = c("Sun", "Mon", "Tue", "Wed", "Thr", "Fri", "Sat")) +
    ylim(lb_chart, 1)
  

})

``` 

<!--
charts{.mobile}
-----------------------------------------------------------------------
### Yearly

```{r}
renderPlot({
target_season() %>%
  group_by(timestamp) %>%
  summarise(ratio = mean(ratio)) %>%
  mutate(
    md = update(timestamp, year = 2018),
    year = year %>% factor
  ) %>%
  ggplot(aes(md, ratio)) +
    geom_line(aes(group = year, color = year)) +
    geom_point(aes(color = year)) +
    ylim(lb_chart,1) +
    scale_x_datetime(date_labels="%b-%d", minor_breaks = date_breaks("day")) +
    xlab("") +
    theme(legend.position = "top")
  })
```

### Monthly

```{r}
renderPlot({
target_season() %>%
  #filter(year == newest_year) %>%
  mutate(
    dom = day(timestamp) %>% factor,
    month = month(timestamp, label = TRUE)
  ) %>%
  group_by(dom, month) %>%
  summarise(
    ratio.mean = mean(ratio),
    ratio.max = max(ratio),
    ratio.min = min(ratio)
  ) %>%
  ungroup %>%
  ggplot(aes(dom, ratio.mean)) +
    geom_line(aes(group = month, color = month)) +
    geom_pointrange(aes(ymin = ratio.min, ymax = ratio.max, color = month)) +
    coord_cartesian(ylim=c(lb_chart,1)) +
    xlab("Day of Month") + ylab("ratio") +
    theme(legend.position = "top")

  })
``` 

### Weekly
```{r}
renderPlot({
target_season() %>%
  group_by(timestamp) %>%
  summarise(ratio = mean(ratio)) %>%
  mutate(dow = wday(timestamp, label = TRUE, locale = "C")) %>%
  ggplot(aes(dow, ratio)) +
    geom_boxplot() +
    ylim(lb_chart, 1) +
    xlab("Day of Week") + 
    theme(legend.position = "top")
})
```
-->


Timing analysis
=================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------
```{r}
years <- year(amaten$date)
selectInput(
  "t_year",
  label = "filter year",
  choices = years,
  multiple = TRUE,
  selected = years
)

months <- month(amaten$date, label = TRUE, locale = "C")
selectInput(
  "t_month",
  label = "filter month",
  choices = months,
  multiple = TRUE,
  selected = months
)

yms <- floor_date(amaten$date, "month") %>% format("%Y-%m")
selectInput(
  "t_ym",
  label = "filter yearmonth",
  choices = yms,
  multiple = TRUE,
  selected = yms
)


numericInput(
  "t_ranker",
  label = "Target rank. Include top of:",
  value = 5,
  min = 1
)

```

Chart
-----------------------------------------

### hourly distribution
```{r}
target_timing <- reactive({
amaten %>%
  filter(
    year(timestamp) %in% input$t_year,
    month(timestamp, label = TRUE, locale = "C") %in% input$t_month,
    (floor_date(timestamp, "month") %>% format("%Y-%m")) %in% input$t_ym
    ) %>%
  arrange(timestamp, ratio) %>%
  group_by(timestamp) %>%
  mutate(rank = row_number()) %>%
  filter(rank <= input$t_ranker) %>%
  ungroup
})

renderPlot({
target_timing() %>%
  mutate( hour = hour(timestamp) %>% factor) %>%
  group_by(hour) %>%
  summarise(ratio = mean(ratio)) %>%
  ggplot(aes(hour, ratio)) +
    geom_point() + geom_line(group = 1)
})
 

```



Forecast
================================================

now developing


Control
================================================

now developing

```{r control}
#textInput(
#  "pw",
#  label = "pw"
#)
#
#numericInput(
#  "inp_samplerate",
#  label = "change sample rate",
#  value = 3,
#  min = 1
#)
#
#actionButton(
#  "submit_samplerate",
#  label="submit"
#)
#
#br()
#br()
#
#actionButton(
#  "observe",
#  label="observe"
#)
#

```

